const { chromium } = require('/opt/browser-tests/node_modules/playwright');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const page = await browser.newPage({viewport:{width:1280,height:720},hasTouch:true});
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 page.on('console',m=>{if(m.type()==='error')console.log('CONSOLE',m.text());});
 await page.goto(process.env.GAME_URL || 'http://localhost:8099');
 await page.click('#title-screen');
 await page.waitForFunction(()=>!!window.gameInstance,{timeout:60000});
 await page.click('#tab-solo');
 const updateConfirmBtn = await page.$('#btn-update-confirm');
 if (updateConfirmBtn) {
   await updateConfirmBtn.click();
   await page.waitForSelector('#update-modal', { state: 'hidden', timeout: 5000 });
 }
 await page.waitForSelector('[data-screen="solo"]:not([hidden])', { timeout: 5000 });
 await page.click('#course-confirm'); await page.click('#btn-start-solo');
 await page.waitForFunction(()=>window.gameInstance.isRunning);
 await page.evaluate(() => window.gameInstance.inputManager.setAutoAccelerate(false));
 const getState=()=>page.evaluate(()=>({...gameInstance.inputManager.state}));
 await page.keyboard.down('ArrowRight'); assert.equal((await getState()).steering,1);
 await page.keyboard.up('ArrowRight'); assert.equal((await getState()).steering,0);
 console.log('PASS: 右キーの方向と解放');
 await page.keyboard.down('w');
 await page.waitForFunction(()=>gameInstance.localPlayerKart.speed>1);
 await page.evaluate(()=>window.dispatchEvent(new Event('blur')));
 assert.equal((await getState()).accelerating,0); await page.keyboard.up('w');
 console.log('PASS: 実走行とフォーカス喪失時の入力解除');
 await page.keyboard.press('e');
 await page.waitForFunction(()=>!gameInstance.inputManager.state.useItemTrigger);
 console.log('PASS: 未所持時の発射予約を消費');
 await page.click('#btn-open-pause'); await page.keyboard.down('w');
 assert.equal((await getState()).accelerating,0); await page.keyboard.up('w');
 await page.click('#btn-pause-resume');
 await page.locator('#ctrl-accel').hover(); await page.mouse.down();
 assert.equal((await getState()).accelerating,1);
 await page.mouse.move(640,360); await page.mouse.up();
 assert.equal((await getState()).accelerating,0);
 console.log('PASS: ポーズ中の入力遮断とボタン外での解放');
 const hudResult=await page.evaluate(()=>{
  const hud=gameInstance.hud; gameInstance.isPaused=true;
  const state={holdingItem:{icon:'banana'},boostTimer:1};
  hud.update(state); const icon=hud.itemIconEl.firstChild;
  for(let i=0;i<120;i++)hud.update(state);
  return {same:icon===hud.itemIconEl.firstChild,boost:!hud.speedlinesCanvas.classList.contains('hidden')};
 });
 assert.equal(hudResult.same,true); assert.equal(hudResult.boost,true);
 console.log('PASS: HUD 120回更新でアイコン再生成0回、ブースト演出表示');

 const gameState = await page.evaluate(() => {
   const input = gameInstance.inputManager;
   input.resetState(); input.setControlMode('stick');
   const stick = document.getElementById('ctrl-stick');
   const rect = stick.getBoundingClientRect();
   const touch = new Touch({identifier:7,target:stick,clientX:rect.right-5,clientY:rect.top+rect.height/2});
   stick.dispatchEvent(new TouchEvent('touchstart',{changedTouches:[touch],bubbles:true,cancelable:true}));
   const steering = input.state.steering;
   window.dispatchEvent(new TouchEvent('touchcancel',{changedTouches:[touch]}));
   return {steering, cleared:input.state.steering};
 });
 assert.ok(gameState.steering > 0); assert.equal(gameState.cleared,0);
 console.log('PASS: スティック右入力とタッチキャンセル（合成イベント）');
 await page.evaluate(()=>{gameInstance.restartRace();});
 await page.waitForFunction(()=>gameInstance.isRunning && !gameInstance.isPaused);
 assert.equal((await getState()).accelerating,0);
 console.log('PASS: リスタート時の入力リセット');
 await page.screenshot({path:'/tmp/race.png'});
 assert.deepEqual(errors,[]); console.log('PASS: ブラウザ例外0件');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
